default:
  artifacts:
    expire_in: 1 day

  before_script:
    - if [ "$CI_COMMIT_TAG" != "" ]; then SUS_FRONTEND_VERSION_TAG=$( echo $CI_COMMIT_TAG | sed "s/release\///" ); else SUS_FRONTEND_VERSION_TAG=latest; fi
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

  tags:
    - linux
    - shell
    - docker

variables:
  SUS_FRONTEND_VERSION_TAG: latest

stages: # List of stages for jobs, and their order of execution
  - info
  - build
  - push

docker:
  stage: info
  script:
    - docker info

environment:
  stage: info
  script:
    - echo "!!!!!  CI_COMMIT_TAG    -  $CI_COMMIT_TAG "
    - echo "!!!!!  SUS_FRONTEND_VERSION_TAG  -  $SUS_FRONTEND_VERSION_TAG "
    - export

build-job: # This job runs in the build stage, which runs first.
  stage: build
  script:
    - docker build
      -f ./Dockerfile
      -t ${CI_REGISTRY_IMAGE}/sus-frontend-v1:${SUS_FRONTEND_VERSION_TAG}
      .

push-image:
  stage: push
  script:
    - docker push ${CI_REGISTRY_IMAGE}/sus-frontend-v1:${SUS_FRONTEND_VERSION_TAG}


